### ISSUE TITLE
Installation on magento 1.14.3.8 - FPC issues ?

### ISSUE THREAD

**Issue by subbu1993** [queueit/KnownUser.V3.MagentoV1#1]
Hey Queue it team,

We are planning to install this module on magento version EE 1.14.3.8. 

I noticed the readme states that there could be issues when using this module along with FPC. And, as you know 1.14.3.8 provides full page caching OOB. 

Can you share what some of these problems are ?

**Comment by sarooghi** [comment]
Hi,
If FPC is enabled then server code of cached pages would not be called for each request (serving page from cache) so users won't be redirected to queue.  
To solve the problem you need to exclude the static page URLs from the queue setup and add a javascript file from Queue-it in your static pages to be able to queue users on ajax calls and not page requests. 
**Please contact support@queue-it.com we can arrange a call and go through your custom scenario.**

**Comment by subbu1993** [comment]
Thanks
