### ISSUE TITLE
Observer method is missing

### ISSUE THREAD

**Issue by subbu1993** [queueit/KnownUser.V3.MagentoV1#2]
https://github.com/queueit/KnownUser.V3.MagentoV1/blob/master/src/app/code/community/Queueit/Knownuser/etc/config.xml#L75

Hey Queue it team,

the observer which runs on place order success seems to be missing declaration and definition in the Observer.php file

Was this accidentally removed - or do we have to define what this method should be doing ?

**Comment by sarooghi** [comment]
Hi,
Thank you for the feedback.
It is a bug checkout_onepage_controller_success_action is gone and should be removed from config.
We will update the repo.
